In [13]:
import pandas as pd
import os

In [14]:
import_tech = "Import_technology.csv"
import_tech_df = pd.read_csv(import_tech, sep="\t")

In [15]:
list(import_tech_df)

['Data Source,"World Development Indicators",']

In [16]:
# Get the contents of row 2
row_2_data = import_tech_df.iloc[1]
# Convert row 2 data to a list
columns = row_2_data.tolist()
columns

['Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022",']

In [17]:
# Split the column on the comma and place in a list.
for column in columns:
    column_names = column.split(",")
print(len(column_names))

68

In [18]:
split_data = import_tech_df['Data Source,"World Development Indicators",'].str.split(',', n=68, expand=True)

# Create a new DataFrame to store the cleaned data with appropriate column names
cleaned_import_tech_df = pd.DataFrame(
    {
        'Country Name': split_data[0],
        'Country Code': split_data[1],
        'Indicator Name': split_data[2],
        'Indicator Code': split_data[3],
    }
)

# Concatenate the remaining columns from split_data to cleaned_atm_df
cleaned_import_tech_df = pd.concat([cleaned_import_tech_df, split_data.iloc[:, 4:]], axis=1)
cleaned_import_tech_df = cleaned_import_tech_df.drop(index=0).reset_index(drop=True)
# Display the cleaned DataFrame
cleaned_import_tech_df.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,Country Name,"""Country Code""","""Indicator Name""","""Indicator Code""","""1960""","""1961""","""1962""","""1963""","""1964""","""1965""",...,"""2015""","""2016""","""2017""","""2018""","""2019""","""2020""","""2021""","""2022""",,None
1,Aruba,"""ABW""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""48.0146361295568""","""46.9069323454773""","""47.1085055650574""","""44.0156384883303""","""47.443127362044""","""46.7423534600308""","""46.8546854829077""","""45.20404216062""","""47.261112303909""","""45.7147906534196"",""42.6830881241231"","
2,Africa Eastern and Southern,"""AFE""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""47.7987330918209""","""47.4354846832054""","""48.2819787544865""","""44.6888451947343""","""45.2022915180981""","""42.5270898717281""","""41.1691797379926""","""38.3355161455078""","""43.6961943060344""","""41.8167117883715"",""39.1087510570482"","
3,Afghanistan,"""AFG""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""29.5147855547543""","""19.5550846845568""","""24.480701675051""","""13.177997594308""","""10.9855953667733""","""9.26027933204912""","""13.5105997661582""","""12.0688453489793""","""12.1766633350475""",""""","""","
4,Africa Western and Central,"""AFW""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""34.1799179713274""","""37.3804951291666""","""40.6431870494634""","""38.0986992179466""","""38.7072032823083""","""43.0132996621098""","""46.5018470068483""","""48.7914646628013""","""49.4415036387868""","""42.3393475917652"","""","

In [19]:
# Assign row 0 as column names
cleaned_import_tech_df.columns = cleaned_import_tech_df.iloc[0]
cleaned_import_tech_df.columns = cleaned_import_tech_df.columns.str.replace('"', '')  # Remove any quotation marks from column names

# Drop row 0 from the DataFrame
cleaned_import_tech_df = cleaned_import_tech_df.drop(index=0).reset_index(drop=True)

# Display the cleaned DataFrame
cleaned_import_tech_df.sample(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
204,South Asia,"""SAS""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""45.3620581045929""","""44.2081727995895""","""43.1367511554217""","""44.5828408122271""","""43.9527548547943""","""43.6481322262563""","""45.0487969542167""","""49.8714646353796""","""58.9677313241864""","""55.104080315297"",""49.7096131979512"","
43,Congo,Dem. Rep.,"""COD""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""",...,"""27.6054748878341""","""35.3993551992407""","""26.7275459978343""","""23.3228215616993""","""28.0913907255515""","""43.5495218340878""","""22.2391698470469""","""29.3902879095187""","""26.3187880166321""","""30.6572162498912"",""35.1812602359523"","""","
80,Gabon,"""GAB""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""51.9311316692546""","""50.9075922429038""","""45.9186969753643""","""51.0985083119652""","""""","""""","""""","""""","""""",""""","""","
246,Tanzania,"""TZA""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""11.3019246982854""","""10.3662550894194""","""13.2835937266815""","""12.6000077640966""","""15.206764911796""","""18.6928065654824""","""25.7647399522423""","""20.7138226625403""","""33.7068869710844""",""""","""","
55,Germany,"""DEU""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""41.7954341246936""","""43.528420497139""","""44.3035863230079""","""46.9859251829654""","""48.8544835974217""","""49.7530437847189""","""49.5802806241033""","""50.1982597098718""","""57.9968471361995""","""53.2606247551188"",""47.2582180146447"","

In [20]:
# Define a function to remove double quotes from each cell
def remove_quotes(cell_value):
    if cell_value is not None:
        return cell_value.replace('"', '')
    else:
        return cell_value

# Use applymap() to remove double quotes from the entire DataFrame
cleaned_import_tech_df_final = cleaned_import_tech_df.applymap(remove_quotes)

# Display the first five rows of the cleaned DataFrame
cleaned_import_tech_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,48.0146361295568,46.9069323454773,47.1085055650574,44.0156384883303,47.443127362044,46.7423534600308,46.8546854829077,45.20404216062,47.261112303909,"45.7147906534196,42.6830881241231,"
1,Africa Eastern and Southern,AFE,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,47.7987330918209,47.4354846832054,48.2819787544865,44.6888451947343,45.2022915180981,42.5270898717281,41.1691797379926,38.3355161455078,43.6961943060344,"41.8167117883715,39.1087510570482,"
2,Afghanistan,AFG,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,29.5147855547543,19.5550846845568,24.480701675051,13.177997594308,10.9855953667733,9.26027933204912,13.5105997661582,12.0688453489793,12.1766633350475,",,"
3,Africa Western and Central,AFW,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,34.1799179713274,37.3804951291666,40.6431870494634,38.0986992179466,38.7072032823083,43.0132996621098,46.5018470068483,48.7914646628013,49.4415036387868,"42.3393475917652,,"
4,Angola,AGO,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,77.8819177576468,74.5800864859563,75.4242915272779,72.3656604104067,65.6042693292308,64.8334241373523,53.8924502841559,49.964906021409,43.5797908850304,"46.2582402150242,47.2867081345289,"

In [21]:
# Convert columns to float data type
for column in cleaned_import_tech_df_final.columns[60:67]:
    cleaned_import_tech_df_final[column] = pd.to_numeric(cleaned_import_tech_df_final[column], errors='coerce')

# Display the DataFrame with the specified columns converted to float
cleaned_import_tech_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,48.0146361295568,46.906932,47.108506,44.015638,47.443127,46.742353,46.854685,45.204042,47.261112303909,"45.7147906534196,42.6830881241231,"
1,Africa Eastern and Southern,AFE,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,47.7987330918209,47.435485,48.281979,44.688845,45.202292,42.527090,41.169180,38.335516,43.6961943060344,"41.8167117883715,39.1087510570482,"
2,Afghanistan,AFG,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,29.5147855547543,19.555085,24.480702,13.177998,10.985595,9.260279,13.510600,12.068845,12.1766633350475,",,"
3,Africa Western and Central,AFW,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,34.1799179713274,37.380495,40.643187,38.098699,38.707203,43.013300,46.501847,48.791465,49.4415036387868,"42.3393475917652,,"
4,Angola,AGO,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,77.8819177576468,74.580086,75.424292,72.365660,65.604269,64.833424,53.892450,49.964906,43.5797908850304,"46.2582402150242,47.2867081345289,"

In [22]:
cleaned_import_tech_df_final.dtypes

0
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960               object
                   ...
2020              float64
2021              float64
2022              float64
                   object
None               object
Length: 69, dtype: object

In [23]:
# Calculate the average for each row in columns 5 to 68
average = cleaned_import_tech_df_final.iloc[:, 60:67].mean(axis=1)
# Add the average values as a new column named "Average" to the DataFrame
cleaned_import_tech_df_final['Average_%_techimport'] = average
cleaned_import_tech_df_final

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,,None,Average_%_techimport
0,Aruba,ABW,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,46.906932,47.108506,44.015638,47.443127,46.742353,46.854685,45.204042,47.261112303909,"45.7147906534196,42.6830881241231,",46.325041
1,Africa Eastern and Southern,AFE,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,47.435485,48.281979,44.688845,45.202292,42.527090,41.169180,38.335516,43.6961943060344,"41.8167117883715,39.1087510570482,",43.948627
2,Afghanistan,AFG,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,19.555085,24.480702,13.177998,10.985595,9.260279,13.510600,12.068845,12.1766633350475,",,",14.719872
3,Africa Western and Central,AFW,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,37.380495,40.643187,38.098699,38.707203,43.013300,46.501847,48.791465,49.4415036387868,"42.3393475917652,,",41.876599
4,Angola,AGO,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,74.580086,75.424292,72.365660,65.604269,64.833424,53.892450,49.964906,43.5797908850304,"46.2582402150242,47.2867081345289,",65.237870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,27.409669,35.617622,22.894213,20.197052,24.403242,30.853203,28.592954,34.3279528958262,"27.9791089857852,26.3630888054195,",27.138279
262,Yemen,Rep.,YEM,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,...,26.151205,26.908548,30.890550,22.419719,30.265425,NaN,NaN,,",,,",27.327089
263,South Africa,ZAF,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,12.8491620111732,13.3720930232558,17.8010471204188,...,35.175663,34.612568,37.007218,41.472321,39.961146,37.613985,39.428475,51.7069073563088,"49.0876783952431,38.8548280521944,",37.895911
264,Zambia,ZMB,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,29.340612,22.629608,15.319847,16.689237,16.847921,17.708986,18.154822,10.123607541205,"24.0865706955986,14.2097391681072,",19.527290
265,Zimbabwe,ZWE,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,32.089111,31.679771,38.945053,44.666960,33.388529,27.377080,27.777004,38.2106498052801,",,",33.703358

In [12]:
techimport_machine_df=cleaned_import_tech_df_final[['Country Name','Average_%_techimport']]
techimport_machine_df.sample(50)

0                                         Country Name  Average_%_techimport
238  Middle East & North Africa (IDA & IBRD countries)             27.225444
88                                   Equatorial Guinea                   NaN
248                                            Ukraine             28.147858
199                                   French Polynesia             20.440180
261                                             Kosovo             27.138279
75                                             Finland             56.777996
164                           Northern Mariana Islands                   NaN
22                                             Bahrain             12.212899
147                           St. Martin (French part)                   NaN
64       Europe & Central Asia (excluding high income)             41.157940
245                                             Tuvalu             51.097365
67                                               Egypt             29.247895
27                                             Bermuda             32.529456
2                                          Afghanistan             14.719872
50                                                Cuba                   NaN
133                                          St. Lucia             48.901546
24                              Bosnia and Herzegovina             20.738678
146                                          Macao SAR             42.389034
131                                            Liberia             53.366088
237                                        Timor-Leste             63.045799
65                               Europe & Central Asia             52.843919
212                                         San Marino                   NaN
149                                             Monaco                   NaN
30                                            Barbados             69.682395
182                                               Oman             31.509833
31                                   Brunei Darussalam             50.100984
35                                              Canada             38.991560
236  Latin America & the Caribbean (IDA & IBRD coun...             41.142536
78                                       Faroe Islands                   NaN
213                                            Somalia                   NaN
204                                         South Asia             44.921273
63                                 East Asia & Pacific             38.349577
48                                          Costa Rica             33.323529
211                                        El Salvador             22.576273
107                                           IDA only             31.943204
189                                   Papua New Guinea             70.737935
175                                          Nicaragua             26.268500
43                                               Congo             29.817156
176                                        Netherlands             68.442287
226                                         Seychelles             61.309578
25                                             Belarus             43.791527
208                                          Singapore             51.497348
138                                          Sri Lanka             14.694229
92                                           Guatemala             20.379286
119                                              Japan             61.832337
18                                               Benin             25.698614
68                                           Euro area             54.817293
214                                             Serbia             43.005362
44                                               Congo             56.986950
229                                               Chad                   NaN

In [24]:
# Create the "Output_Jibek" directory if it doesn't exist
output_directory = "../Output_Jibek"
if not os.path.exists(output_directory):
    os.makedirs(output_directory)
# Save the cleaned DataFrame to a CSV file in the specified directory
techimport_machine_df.to_csv(os.path.join(output_directory, 'techimport_machine_df'), index=False)