In [48]:
import pandas as pd
import os

In [67]:
gdp = "GDP_Growth.csv"
gdp_df = pd.read_csv(gdp, sep="\t")
gdp_df.head(10)

         Data Source,"World Development Indicators",
0                    Last Updated Date,"2023-06-29",
1  Country Name,"Country Code","Indicator Name","...
2  Aruba,"ABW","GDP per capita growth (annual %)"...
3  Africa Eastern and Southern,"AFE","GDP per cap...
4  Afghanistan,"AFG","GDP per capita growth (annu...
5  Africa Western and Central,"AFW","GDP per capi...
6  Angola,"AGO","GDP per capita growth (annual %)...
7  Albania,"ALB","GDP per capita growth (annual %...
8  Andorra,"AND","GDP per capita growth (annual %...
9  Arab World,"ARB","GDP per capita growth (annua...

In [68]:
list(gdp_df)

['Data Source,"World Development Indicators",']

In [69]:
# Get the contents of row 2
row_2_data = gdp_df.iloc[1]
# Convert row 2 data to a list
columns = row_2_data.tolist()
columns

['Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022",']

In [70]:
# Split the column on the comma and place in a list.
for column in columns:
    column_names = column.split(",")
print(len(column_names))

68

In [71]:
split_data = gdp_df['Data Source,"World Development Indicators",'].str.split(',', n=68, expand=True)

# Create a new DataFrame to store the cleaned data with appropriate column names
cleaned_gdp_df = pd.DataFrame(
    {
        'Country Name': split_data[0],
        'Country Code': split_data[1],
        'Indicator Name': split_data[2],
        'Indicator Code': split_data[3],
    }
)

# Concatenate the remaining columns from split_data to cleaned_atm_df
cleaned_gdp_df = pd.concat([cleaned_gdp_df, split_data.iloc[:, 4:]], axis=1)
cleaned_gdp_df = cleaned_gdp_df.drop(index=0).reset_index(drop=True)
# Display the cleaned DataFrame
cleaned_gdp_df.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,Country Name,"""Country Code""","""Indicator Name""","""Indicator Code""","""1960""","""1961""","""1962""","""1963""","""1964""","""1965""",...,"""2015""","""2016""","""2017""","""2018""","""2019""","""2020""","""2021""","""2022""",,None
1,Aruba,"""ABW""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""2.88516618544072""","""1.51593791406077""","""4.91713876742246""","""4.73833038397655""","""0.181216309197723""","""-18.6983243537002""","""17.2253004018797""","""""",,None
2,Africa Eastern and Southern,"""AFE""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""-2.34297354000095""","""5.09399196578835""","""2.33079606875697""","""1.72402096043484""","""2.43621527890161""",...,"""0.166839637757079""","""-0.490259075567408""","""-0.10588633336323""","""-0.169822405441494""","""-0.587557018399707""","""-5.42166221698315""","""1.68355673118708""","""0.842506639677993""",,None
3,Afghanistan,"""AFG""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""-1.66641641520391""","""-0.345802496981889""","""-0.253593781811986""","""-1.68857659267114""","""0.932833388709597""","""-5.3646659309623""","""-22.9291944307147""","""""",,None
4,Africa Western and Central,"""AFW""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""-0.255511351747927""","""1.59294217712238""","""4.97870998351004""","""3.1302314152464""","""1.79876056473303""",...,"""0.0260160622438406""","""-2.51927409834653""","""-0.38269079571522""","""0.140162280475892""","""0.563580469542387""","""-3.45312417907287""","""1.37216006946974""","""1.19266768111382""",,None

In [72]:
# Assign row 0 as column names
cleaned_gdp_df.columns = cleaned_gdp_df.iloc[0]
cleaned_gdp_df.columns = cleaned_gdp_df.columns.str.replace('"', '')  # Remove any quotation marks from column names

# Drop row 0 from the DataFrame
cleaned_gdp_df = cleaned_gdp_df.drop(index=0).reset_index(drop=True)

# Display the cleaned DataFrame
cleaned_gdp_df.sample(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
41,Cote d'Ivoire,"""CIV""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""5.94256321117601""","""-2.56940358009668""","""10.1336407468267""","""13.1246567637934""","""-6.80857097944264""",...,"""4.46388996246519""","""4.44236105899517""","""4.66846126117883""","""2.18660849615524""","""3.85584194134769""","""-0.782841474086808""","""4.40481596430489""","""4.15512756791803""",,None
188,Palau,"""PLW""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""7.55115034053378""","""-0.206754779293234""","""-4.19174162710635""","""-0.0431972500937974""","""0.104575692886286""","""-9.39042502432173""","""-13.5833703210534""","""""",,None
172,New Caledonia,"""NCL""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""""","""""","""""","""3.86193162960504""","""-1.42544609939537""","""-2.8370256184394""","""-2.88416951867761""","""""",,None
124,Kiribati,"""KIR""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""8.24412516251402""","""-1.99479304924535""","""-1.35302964447919""","""3.48097512698243""","""-3.7213810908485""","""-3.38537208031016""","""5.84720586765961""","""-0.262393128200458""",,None
122,Kyrgyz Republic,"""KGZ""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""1.75886440985292""","""2.23180526571734""","""2.73409189148251""","""1.7132091060235""","""2.43933520707868""","""-10.1204455334221""","""4.39230761367301""","""5.26821057703893""",,None

In [73]:
# Define a function to remove double quotes from each cell
def remove_quotes(cell_value):
    if cell_value is not None:
        return cell_value.replace('"', '')
    else:
        return cell_value

# Use applymap() to remove double quotes from the entire DataFrame
cleaned_gdp_df_final = cleaned_gdp_df.applymap(remove_quotes)

# Display the first five rows of the cleaned DataFrame
cleaned_gdp_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,2.88516618544072,1.51593791406077,4.91713876742246,4.73833038397655,0.181216309197723,-18.6983243537002,17.2253004018797,,,None
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.34297354000095,5.09399196578835,2.33079606875697,1.72402096043484,2.43621527890161,...,0.166839637757079,-0.490259075567408,-0.10588633336323,-0.169822405441494,-0.587557018399707,-5.42166221698315,1.68355673118708,0.842506639677993,,None
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-1.66641641520391,-0.345802496981889,-0.253593781811986,-1.68857659267114,0.932833388709597,-5.3646659309623,-22.9291944307147,,,None
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511351747927,1.59294217712238,4.97870998351004,3.1302314152464,1.79876056473303,...,0.0260160622438406,-2.51927409834653,-0.38269079571522,0.140162280475892,0.563580469542387,-3.45312417907287,1.37216006946974,1.19266768111382,,None
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-2.64297533030704,-6.01189077751143,-3.63069503801748,-4.67666958432599,-4.01711416103254,-8.67243212911843,-1.95459800636894,-0.096754729759283,,None

In [74]:
# Convert columns 5 to 68 to float data type
for column in cleaned_gdp_df_final.columns[5:69]:
    cleaned_gdp_df_final[column] = pd.to_numeric(cleaned_gdp_df_final[column], errors='coerce')

# Display the DataFrame with the specified columns converted to float
cleaned_gdp_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,NaN,NaN,NaN,NaN,NaN,...,2.885166,1.515938,4.917139,4.738330,0.181216,-18.698324,17.225300,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.342974,5.093992,2.330796,1.724021,2.436215,...,0.166840,-0.490259,-0.105886,-0.169822,-0.587557,-5.421662,1.683557,0.842507,NaN,NaN
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,NaN,NaN,NaN,NaN,NaN,...,-1.666416,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.929194,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511,1.592942,4.978710,3.130231,1.798761,...,0.026016,-2.519274,-0.382691,0.140162,0.563580,-3.453124,1.372160,1.192668,NaN,NaN
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,NaN,NaN,NaN,NaN,NaN,...,-2.642975,-6.011891,-3.630695,-4.676670,-4.017114,-8.672432,-1.954598,-0.096755,NaN,NaN

In [75]:
cleaned_gdp_df_final.dtypes

0
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960               object
                   ...
2020              float64
2021              float64
2022              float64
                  float64
None              float64
Length: 69, dtype: object

In [76]:
# Calculate the average for each row in columns 5 to 68
average = cleaned_gdp_df_final.iloc[:, 5:69].mean(axis=1)
# Add the average values as a new column named "Average" to the DataFrame
cleaned_gdp_df_final['Average_gdp_growth'] = average

In [77]:
cleaned_gdp_df_final

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,,None,Average_gdp_growth
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,NaN,NaN,NaN,NaN,NaN,...,1.515938,4.917139,4.738330,0.181216,-18.698324,17.225300,NaN,NaN,NaN,2.222356
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.342974,5.093992,2.330796,1.724021,2.436215,...,-0.490259,-0.105886,-0.169822,-0.587557,-5.421662,1.683557,0.842507,NaN,NaN,0.388004
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,NaN,NaN,NaN,NaN,NaN,...,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.929194,NaN,NaN,NaN,1.237137
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511,1.592942,4.978710,3.130231,1.798761,...,-2.519274,-0.382691,0.140162,0.563580,-3.453124,1.372160,1.192668,NaN,NaN,0.931831
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,NaN,NaN,NaN,NaN,NaN,...,-6.011891,-3.630695,-4.676670,-4.017114,-8.672432,-1.954598,-0.096755,NaN,NaN,-0.120052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,NaN,NaN,NaN,NaN,NaN,...,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.924753,NaN,NaN,4.235257
262,Yemen,Rep.,YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,...,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN,NaN,NaN,-1.135928
263,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,0.977924,3.061899,4.165498,4.685237,2.892205,...,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.187663,NaN,NaN,0.705042
264,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-1.787685,-5.541489,0.023361,8.686086,12.972033,...,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.895518,NaN,NaN,0.197330
265,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,3.076210,-1.666989,2.985427,-4.143906,1.682986,...,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.328184,NaN,NaN,0.476139

In [78]:
gdpgrowth_machine_df=cleaned_gdp_df_final[['Country Name','Average_gdp_growth']]
gdpgrowth_machine_df.sample(5)

0     Country Name  Average_gdp_growth
9        Argentina            1.049743
71         Estonia            4.272539
26          Belize            2.405764
41   Cote d'Ivoire            0.930284
262          Yemen           -1.135928

In [79]:
# Create the "Output_Jibek" directory if it doesn't exist
output_directory = "../Output_Jibek"
if not os.path.exists(output_directory):
    os.makedirs(output_directory)
# Save the cleaned DataFrame to a CSV file in the specified directory
gdpgrowth_machine_df.to_csv(os.path.join(output_directory, 'gdpgrowth_machine_df'), index=False)