In [17]:
import pandas as pd
import os

In [18]:
gdp = "GDP_Growth.csv"
gdp_df = pd.read_csv(gdp, sep="\t")
gdp_df.head(10)

         Data Source,"World Development Indicators",
0                    Last Updated Date,"2023-06-29",
1  Country Name,"Country Code","Indicator Name","...
2  Aruba,"ABW","GDP per capita growth (annual %)"...
3  Africa Eastern and Southern,"AFE","GDP per cap...
4  Afghanistan,"AFG","GDP per capita growth (annu...
5  Africa Western and Central,"AFW","GDP per capi...
6  Angola,"AGO","GDP per capita growth (annual %)...
7  Albania,"ALB","GDP per capita growth (annual %...
8  Andorra,"AND","GDP per capita growth (annual %...
9  Arab World,"ARB","GDP per capita growth (annua...

In [19]:
list(gdp_df)

['Data Source,"World Development Indicators",']

In [20]:
# Get the contents of row 2
row_2_data = gdp_df.iloc[1]
# Convert row 2 data to a list
columns = row_2_data.tolist()
columns

['Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022",']

In [21]:
# Split the column on the comma and place in a list.
for column in columns:
    column_names = column.split(",")
print(len(column_names))

68

In [22]:
split_data = gdp_df['Data Source,"World Development Indicators",'].str.split(',', n=68, expand=True)

# Create a new DataFrame to store the cleaned data with appropriate column names
cleaned_gdp_df = pd.DataFrame(
    {
        'Country Name': split_data[0],
        'Country Code': split_data[1],
        'Indicator Name': split_data[2],
        'Indicator Code': split_data[3],
    }
)

# Concatenate the remaining columns from split_data to cleaned_atm_df
cleaned_gdp_df = pd.concat([cleaned_gdp_df, split_data.iloc[:, 4:]], axis=1)
cleaned_gdp_df = cleaned_gdp_df.drop(index=0).reset_index(drop=True)
# Display the cleaned DataFrame
cleaned_gdp_df.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,Country Name,"""Country Code""","""Indicator Name""","""Indicator Code""","""1960""","""1961""","""1962""","""1963""","""1964""","""1965""",...,"""2015""","""2016""","""2017""","""2018""","""2019""","""2020""","""2021""","""2022""",,None
1,Aruba,"""ABW""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""2.88516618544072""","""1.51593791406077""","""4.91713876742246""","""4.73833038397655""","""0.181216309197723""","""-18.6983243537002""","""17.2253004018797""","""""",,None
2,Africa Eastern and Southern,"""AFE""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""-2.34297354000095""","""5.09399196578835""","""2.33079606875697""","""1.72402096043484""","""2.43621527890161""",...,"""0.166839637757079""","""-0.490259075567408""","""-0.10588633336323""","""-0.169822405441494""","""-0.587557018399707""","""-5.42166221698315""","""1.68355673118708""","""0.842506639677993""",,None
3,Afghanistan,"""AFG""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""-1.66641641520391""","""-0.345802496981889""","""-0.253593781811986""","""-1.68857659267114""","""0.932833388709597""","""-5.3646659309623""","""-22.9291944307147""","""""",,None
4,Africa Western and Central,"""AFW""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""-0.255511351747927""","""1.59294217712238""","""4.97870998351004""","""3.1302314152464""","""1.79876056473303""",...,"""0.0260160622438406""","""-2.51927409834653""","""-0.38269079571522""","""0.140162280475892""","""0.563580469542387""","""-3.45312417907287""","""1.37216006946974""","""1.19266768111382""",,None

In [23]:
# Assign row 0 as column names
cleaned_gdp_df.columns = cleaned_gdp_df.iloc[0]
cleaned_gdp_df.columns = cleaned_gdp_df.columns.str.replace('"', '')  # Remove any quotation marks from column names

# Drop row 0 from the DataFrame
cleaned_gdp_df = cleaned_gdp_df.drop(index=0).reset_index(drop=True)

# Display the cleaned DataFrame
cleaned_gdp_df.sample(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
6,Andorra,"""AND""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""1.25741601269149""","""2.57450458774666""","""-1.41657902035861""","""-0.00387029555736262""","""0.238296569502523""","""-12.7350775611172""","""6.45944053180018""","""7.73271565222045""",,None
34,Central African Republic,"""CAF""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""3.0736281949108""","""-5.4896637926801""","""-2.5915614052098""","""0.0811956533575113""","""-1.09831775021159""",...,"""3.89115882835796""","""2.93809923935532""","""2.59092350135077""","""1.79222030531334""","""0.833009810869896""","""-1.62477557942373""","""-1.21027956389845""","""-2.186536142462""",,None
204,South Asia,"""SAS""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""1.7716362035666""","""0.981180462929274""","""2.79031215715619""","""5.234961939024""","""-2.94360771636796""",...,"""6.03544499293713""","""6.39229513938777""","""5.24682911467991""","""5.0861803978574""","""2.76403766961361""","""-5.72161798697594""","""7.16471102744075""","""5.50329271193381""",,None
90,Grenada,"""GRD""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""5.54341792813746""","""2.88696863002274""","""3.61384842471548""","""3.57597575337994""","""-0.0503174827996276""","""-14.4114869434991""","""3.89188357961443""","""5.101628779715""",,None
86,Gambia,The,"""GMB""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""",...,"""-4.29667510195249""","""1.09705048941071""","""-0.875473406735992""","""2.00630767513326""","""4.43949429425278""","""3.51379371760613""","""-1.95308366905797""","""1.66189201432788""","""2.36165777021206""",

In [24]:
# Define a function to remove double quotes from each cell
def remove_quotes(cell_value):
    if cell_value is not None:
        return cell_value.replace('"', '')
    else:
        return cell_value

# Use applymap() to remove double quotes from the entire DataFrame
cleaned_gdp_df_final = cleaned_gdp_df.applymap(remove_quotes)

# Display the first five rows of the cleaned DataFrame
cleaned_gdp_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,2.88516618544072,1.51593791406077,4.91713876742246,4.73833038397655,0.181216309197723,-18.6983243537002,17.2253004018797,,,None
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.34297354000095,5.09399196578835,2.33079606875697,1.72402096043484,2.43621527890161,...,0.166839637757079,-0.490259075567408,-0.10588633336323,-0.169822405441494,-0.587557018399707,-5.42166221698315,1.68355673118708,0.842506639677993,,None
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-1.66641641520391,-0.345802496981889,-0.253593781811986,-1.68857659267114,0.932833388709597,-5.3646659309623,-22.9291944307147,,,None
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511351747927,1.59294217712238,4.97870998351004,3.1302314152464,1.79876056473303,...,0.0260160622438406,-2.51927409834653,-0.38269079571522,0.140162280475892,0.563580469542387,-3.45312417907287,1.37216006946974,1.19266768111382,,None
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-2.64297533030704,-6.01189077751143,-3.63069503801748,-4.67666958432599,-4.01711416103254,-8.67243212911843,-1.95459800636894,-0.096754729759283,,None

In [25]:
# Convert columns 5 to 68 to float data type
for column in cleaned_gdp_df_final.columns[60:67]:
    cleaned_gdp_df_final[column] = pd.to_numeric(cleaned_gdp_df_final[column], errors='coerce')

# Display the DataFrame with the specified columns converted to float
cleaned_gdp_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,2.88516618544072,1.515938,4.917139,4.738330,0.181216,-18.698324,17.225300,NaN,,None
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.34297354000095,5.09399196578835,2.33079606875697,1.72402096043484,2.43621527890161,...,0.166839637757079,-0.490259,-0.105886,-0.169822,-0.587557,-5.421662,1.683557,0.842507,,None
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-1.66641641520391,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.929194,NaN,,None
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511351747927,1.59294217712238,4.97870998351004,3.1302314152464,1.79876056473303,...,0.0260160622438406,-2.519274,-0.382691,0.140162,0.563580,-3.453124,1.372160,1.192668,,None
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-2.64297533030704,-6.011891,-3.630695,-4.676670,-4.017114,-8.672432,-1.954598,-0.096755,,None

In [26]:
cleaned_gdp_df_final.dtypes

0
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960               object
                   ...
2020              float64
2021              float64
2022              float64
                   object
None               object
Length: 69, dtype: object

In [27]:
# Calculate the average for each row in 2015-2022
average = cleaned_gdp_df_final.iloc[:, 60:67].mean(axis=1)
# Add the average values as a new column named "Average" to the DataFrame
cleaned_gdp_df_final['Average_gdp_growth%'] = average

In [28]:
cleaned_gdp_df_final

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,,None,Average_gdp_growth%
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,1.515938,4.917139,4.738330,0.181216,-18.698324,17.225300,NaN,,None,1.646600
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.34297354000095,5.09399196578835,2.33079606875697,1.72402096043484,2.43621527890161,...,-0.490259,-0.105886,-0.169822,-0.587557,-5.421662,1.683557,0.842507,,None,-0.607018
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.929194,NaN,,None,-4.941500
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511351747927,1.59294217712238,4.97870998351004,3.1302314152464,1.79876056473303,...,-2.519274,-0.382691,0.140162,0.563580,-3.453124,1.372160,1.192668,,None,-0.440931
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-6.011891,-3.630695,-4.676670,-4.017114,-8.672432,-1.954598,-0.096755,,None,-4.151451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.924753,,None,4.150582
262,Yemen,Rep.,YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,...,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,NaN,,,-12.709657
263,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,0.977923938584297,3.06189947695803,4.16549817661469,4.685237419633,2.8922054413778,...,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.187663,,None,-0.380969
264,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-1.78768497310053,-5.54148944363011,0.0233605345168826,8.68608586454545,12.9720329002912,...,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.895518,,None,-0.257922
265,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,3.07620994094849,-1.66698919029021,2.98542723959167,-4.14390578333571,1.68298600753299,...,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.328184,,None,-0.934511

In [29]:
gdpgrowth_machine_df=cleaned_gdp_df_final[['Country Name','Average_gdp_growth%']]
gdpgrowth_machine_df.sample(50)

0                                         Country Name  Average_gdp_growth%
11                                      American Samoa             1.662126
57                                            Dominica            -0.338261
199                                   French Polynesia             0.381159
213                                            Somalia             1.681640
89                                              Greece             1.708486
74            Fragile and conflict affected situations            -0.966098
63                                 East Asia & Pacific             3.384232
106                                          Indonesia             2.983834
252                                         Uzbekistan             3.382649
121                                              Kenya             2.321555
19                                        Burkina Faso             2.129957
80                                               Gabon            -0.914938
245                                             Tuvalu             2.505625
69                                             Eritrea                  NaN
251                                      United States             1.502945
242                                Trinidad and Tobago            -3.299452
31                                   Brunei Darussalam            -0.803440
139                                Lower middle income             2.493778
54                                             Czechia             2.101078
28                                             Bolivia             0.779136
120                                         Kazakhstan             1.056693
126                                              Korea             2.215990
23                                             Bahamas            -1.009476
175                                          Nicaragua             0.757304
162                                         Montenegro             3.095095
215         Sub-Saharan Africa (excluding high income)            -0.535176
87                                       Guinea-Bissau             0.888795
33                                            Botswana             1.984832
0                                                Aruba             1.646600
60                                             Algeria            -0.663419
90                                             Grenada             0.658357
117                                            Jamaica             0.412481
156                                      Middle income             3.025223
253                     St. Vincent and the Grenadines             1.994586
150                                            Moldova             3.630724
128  Latin America & Caribbean (excluding high income)             0.166679
249                                Upper middle income             3.497472
191                           Pre-demographic dividend            -0.742408
138                                          Sri Lanka             0.104957
200                                              Qatar            -0.631995
36                      Central Europe and the Baltics             3.777206
135       Least developed countries: UN classification             1.072646
84                                           Gibraltar                  NaN
116                                              Italy             1.317179
164                           Northern Mariana Islands            -0.816852
105                                          IDA blend             0.640981
50                                                Cuba            -0.759313
71                                             Estonia             2.916697
259                                              World             1.551179
203                                             Rwanda             3.701939

In [30]:
# Create the "Output_Jibek" directory if it doesn't exist
output_directory = "../Output_Jibek"
if not os.path.exists(output_directory):
    os.makedirs(output_directory)
# Save the cleaned DataFrame to a CSV file in the specified directory
gdpgrowth_machine_df.to_csv(os.path.join(output_directory, 'gdpgrowth_machine_df'), index=False)