In [1]:
import pandas as pd
import os

In [2]:
import_tech = "Import_technology.csv"
import_tech_df = pd.read_csv(import_tech, sep="\t")

In [3]:
list(import_tech_df)

['Data Source,"World Development Indicators",']

In [4]:
# Get the contents of row 2
row_2_data = import_tech_df.iloc[1]
# Convert row 2 data to a list
columns = row_2_data.tolist()
columns

['Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022",']

In [5]:
# Split the column on the comma and place in a list.
for column in columns:
    column_names = column.split(",")
print(len(column_names))

68

In [6]:
split_data = import_tech_df['Data Source,"World Development Indicators",'].str.split(',', n=68, expand=True)

# Create a new DataFrame to store the cleaned data with appropriate column names
cleaned_import_tech_df = pd.DataFrame(
    {
        'Country Name': split_data[0],
        'Country Code': split_data[1],
        'Indicator Name': split_data[2],
        'Indicator Code': split_data[3],
    }
)

# Concatenate the remaining columns from split_data to cleaned_atm_df
cleaned_import_tech_df = pd.concat([cleaned_import_tech_df, split_data.iloc[:, 4:]], axis=1)
cleaned_import_tech_df = cleaned_import_tech_df.drop(index=0).reset_index(drop=True)
# Display the cleaned DataFrame
cleaned_import_tech_df.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,Country Name,"""Country Code""","""Indicator Name""","""Indicator Code""","""1960""","""1961""","""1962""","""1963""","""1964""","""1965""",...,"""2015""","""2016""","""2017""","""2018""","""2019""","""2020""","""2021""","""2022""",,None
1,Aruba,"""ABW""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""48.0146361295568""","""46.9069323454773""","""47.1085055650574""","""44.0156384883303""","""47.443127362044""","""46.7423534600308""","""46.8546854829077""","""45.20404216062""","""47.261112303909""","""45.7147906534196"",""42.6830881241231"","
2,Africa Eastern and Southern,"""AFE""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""47.7987330918209""","""47.4354846832054""","""48.2819787544865""","""44.6888451947343""","""45.2022915180981""","""42.5270898717281""","""41.1691797379926""","""38.3355161455078""","""43.6961943060344""","""41.8167117883715"",""39.1087510570482"","
3,Afghanistan,"""AFG""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""29.5147855547543""","""19.5550846845568""","""24.480701675051""","""13.177997594308""","""10.9855953667733""","""9.26027933204912""","""13.5105997661582""","""12.0688453489793""","""12.1766633350475""",""""","""","
4,Africa Western and Central,"""AFW""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""34.1799179713274""","""37.3804951291666""","""40.6431870494634""","""38.0986992179466""","""38.7072032823083""","""43.0132996621098""","""46.5018470068483""","""48.7914646628013""","""49.4415036387868""","""42.3393475917652"","""","

In [7]:
# Assign row 0 as column names
cleaned_import_tech_df.columns = cleaned_import_tech_df.iloc[0]
cleaned_import_tech_df.columns = cleaned_import_tech_df.columns.str.replace('"', '')  # Remove any quotation marks from column names

# Drop row 0 from the DataFrame
cleaned_import_tech_df = cleaned_import_tech_df.drop(index=0).reset_index(drop=True)

# Display the cleaned DataFrame
cleaned_import_tech_df.sample(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
78,Faroe Islands,"""FRO""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""""","""""","""""","""""","""""","""""","""""","""""","""""",""""","""","
128,Latin America & Caribbean (excluding high income),"""LAC""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""40.3068804694001""","""40.1355391513219""","""41.5619647581331""","""43.1035870003068""","""42.6252573720117""","""39.9249395606249""","""39.6781721502139""","""40.0213787126288""","""49.8651261487319""","""40.4430965132367"",""36.305699297181"","
9,Argentina,"""ARG""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""37.4849414784261""","""39.0279108122936""","""39.2966323703185""","""35.7330526448386""","""31.9733822945135""","""31.7075949921335""","""32.4823315992536""","""37.24186026129""","""54.1884687632645""","""56.775951744789"",""39.7792859179771"","
41,Cote d'Ivoire,"""CIV""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""21.0930647705843""","""24.338764928473""","""24.9732898053974""","""24.6047195320718""","""36.4977275731606""","""38.4331580328472""","""30.8947131250182""","""32.4221353080748""","""33.92803011973""","""28.522163949277"","""","
190,Poland,"""POL""","""Communications",computer,etc. (% of service imports,"BoP)""","""BM.GSR.CMCP.ZS""","""""","""""","""""",...,"""47.3154993108633""","""50.2617167407945""","""51.0442225392297""","""51.5106070547068""","""51.3108390564348""","""51.6488768519994""","""52.1862498837101""","""53.1086176768141""","""60.050985050985""","""57.5057643299219"",""54.9550336156466"","

In [8]:
# Define a function to remove double quotes from each cell
def remove_quotes(cell_value):
    if cell_value is not None:
        return cell_value.replace('"', '')
    else:
        return cell_value

# Use applymap() to remove double quotes from the entire DataFrame
cleaned_import_tech_df_final = cleaned_import_tech_df.applymap(remove_quotes)

# Display the first five rows of the cleaned DataFrame
cleaned_import_tech_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,48.0146361295568,46.9069323454773,47.1085055650574,44.0156384883303,47.443127362044,46.7423534600308,46.8546854829077,45.20404216062,47.261112303909,"45.7147906534196,42.6830881241231,"
1,Africa Eastern and Southern,AFE,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,47.7987330918209,47.4354846832054,48.2819787544865,44.6888451947343,45.2022915180981,42.5270898717281,41.1691797379926,38.3355161455078,43.6961943060344,"41.8167117883715,39.1087510570482,"
2,Afghanistan,AFG,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,29.5147855547543,19.5550846845568,24.480701675051,13.177997594308,10.9855953667733,9.26027933204912,13.5105997661582,12.0688453489793,12.1766633350475,",,"
3,Africa Western and Central,AFW,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,34.1799179713274,37.3804951291666,40.6431870494634,38.0986992179466,38.7072032823083,43.0132996621098,46.5018470068483,48.7914646628013,49.4415036387868,"42.3393475917652,,"
4,Angola,AGO,Communications,computer,etc. (% of service imports,BoP),BM.GSR.CMCP.ZS,,,,...,77.8819177576468,74.5800864859563,75.4242915272779,72.3656604104067,65.6042693292308,64.8334241373523,53.8924502841559,49.964906021409,43.5797908850304,"46.2582402150242,47.2867081345289,"

In [9]:
# Convert columns 5 to 68 to float data type
for column in cleaned_import_tech_df_final.columns[5:69]:
    cleaned_import_tech_df_final[column] = pd.to_numeric(cleaned_import_tech_df_final[column], errors='coerce')

# Display the DataFrame with the specified columns converted to float
cleaned_import_tech_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,48.014636,46.906932,47.108506,44.015638,47.443127,46.742353,46.854685,45.204042,47.261112,NaN
1,Africa Eastern and Southern,AFE,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,47.798733,47.435485,48.281979,44.688845,45.202292,42.527090,41.169180,38.335516,43.696194,NaN
2,Afghanistan,AFG,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,29.514786,19.555085,24.480702,13.177998,10.985595,9.260279,13.510600,12.068845,12.176663,NaN
3,Africa Western and Central,AFW,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,34.179918,37.380495,40.643187,38.098699,38.707203,43.013300,46.501847,48.791465,49.441504,NaN
4,Angola,AGO,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,77.881918,74.580086,75.424292,72.365660,65.604269,64.833424,53.892450,49.964906,43.579791,NaN

In [11]:
cleaned_import_tech_df_final.dtypes

0
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960               object
                   ...
2020              float64
2021              float64
2022              float64
                  float64
None              float64
Length: 69, dtype: object

In [14]:
# Calculate the average for each row in columns 5 to 68
average = cleaned_import_tech_df_final.iloc[:, 5:69].mean(axis=1)
# Add the average values as a new column named "Average" to the DataFrame
cleaned_import_tech_df_final['Average_%_techimport'] = average
cleaned_import_tech_df_final

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,,None,Average_gdp_growth,Average_%_techimport
0,Aruba,ABW,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,47.108506,44.015638,47.443127,46.742353,46.854685,45.204042,47.261112,NaN,48.940342,48.940342
1,Africa Eastern and Southern,AFE,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,48.281979,44.688845,45.202292,42.527090,41.169180,38.335516,43.696194,NaN,35.444698,35.444698
2,Afghanistan,AFG,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,24.480702,13.177998,10.985595,9.260279,13.510600,12.068845,12.176663,NaN,16.197945,16.197945
3,Africa Western and Central,AFW,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,40.643187,38.098699,38.707203,43.013300,46.501847,48.791465,49.441504,NaN,43.018899,43.018899
4,Angola,AGO,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,75.424292,72.365660,65.604269,64.833424,53.892450,49.964906,43.579791,NaN,69.893027,69.893027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,35.617622,22.894213,20.197052,24.403242,30.853203,28.592954,34.327953,NaN,36.400553,36.400553
262,Yemen,Rep.,YEM,Communications,computer,NaN,NaN,NaN,NaN,NaN,...,26.908548,30.890550,22.419719,30.265425,NaN,NaN,NaN,NaN,31.879825,31.879825
263,South Africa,ZAF,Communications,computer,etc. (% of service imports,NaN,NaN,12.849162,13.372093,17.801047,...,34.612568,37.007218,41.472321,39.961146,37.613985,39.428475,51.706907,NaN,24.390137,24.390137
264,Zambia,ZMB,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,22.629608,15.319847,16.689237,16.847921,17.708986,18.154822,10.123608,NaN,22.235823,22.235823
265,Zimbabwe,ZWE,Communications,computer,etc. (% of service imports,NaN,NaN,NaN,NaN,NaN,...,31.679771,38.945053,44.666960,33.388529,27.377080,27.777004,38.210650,NaN,32.047039,32.047039

In [ ]:
gdpgrowth_machine_df=cleaned_import_tech_df_final[['Country Name','Average_%_techimport']]
gdpgrowth_machine_df.sample(5)