In [45]:
import pandas as pd
import os

In [46]:
gdp = "GDP_Growth.csv"
gdp_df = pd.read_csv(gdp, sep="\t")
gdp_df.head(10)

         Data Source,"World Development Indicators",
0                    Last Updated Date,"2023-06-29",
1  Country Name,"Country Code","Indicator Name","...
2  Aruba,"ABW","GDP per capita growth (annual %)"...
3  Africa Eastern and Southern,"AFE","GDP per cap...
4  Afghanistan,"AFG","GDP per capita growth (annu...
5  Africa Western and Central,"AFW","GDP per capi...
6  Angola,"AGO","GDP per capita growth (annual %)...
7  Albania,"ALB","GDP per capita growth (annual %...
8  Andorra,"AND","GDP per capita growth (annual %...
9  Arab World,"ARB","GDP per capita growth (annua...

In [47]:
list(gdp_df)

['Data Source,"World Development Indicators",']

In [48]:
# Get the contents of row 2
row_2_data = gdp_df.iloc[1]
# Convert row 2 data to a list
columns = row_2_data.tolist()
columns

['Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022",']

In [49]:
# Split the column on the comma and place in a list.
for column in columns:
    column_names = column.split(",")
print(len(column_names))

68

In [50]:
split_data = gdp_df['Data Source,"World Development Indicators",'].str.split(',', n=68, expand=True)

# Create a new DataFrame to store the cleaned data with appropriate column names
cleaned_gdp_df = pd.DataFrame(
    {
        'Country Name': split_data[0],
        'Country Code': split_data[1],
        'Indicator Name': split_data[2],
        'Indicator Code': split_data[3],
    }
)

# Concatenate the remaining columns from split_data to cleaned_atm_df
cleaned_gdp_df = pd.concat([cleaned_gdp_df, split_data.iloc[:, 4:]], axis=1)
cleaned_gdp_df = cleaned_gdp_df.drop(index=0).reset_index(drop=True)
# Display the cleaned DataFrame
cleaned_gdp_df.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,Country Name,"""Country Code""","""Indicator Name""","""Indicator Code""","""1960""","""1961""","""1962""","""1963""","""1964""","""1965""",...,"""2015""","""2016""","""2017""","""2018""","""2019""","""2020""","""2021""","""2022""",,None
1,Aruba,"""ABW""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""2.88516618544072""","""1.51593791406077""","""4.91713876742246""","""4.73833038397655""","""0.181216309197723""","""-18.6983243537002""","""17.2253004018797""","""""",,None
2,Africa Eastern and Southern,"""AFE""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""-2.34297354000095""","""5.09399196578835""","""2.33079606875697""","""1.72402096043484""","""2.43621527890161""",...,"""0.166839637757079""","""-0.490259075567408""","""-0.10588633336323""","""-0.169822405441494""","""-0.587557018399707""","""-5.42166221698315""","""1.68355673118708""","""0.842506639677993""",,None
3,Afghanistan,"""AFG""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""-1.66641641520391""","""-0.345802496981889""","""-0.253593781811986""","""-1.68857659267114""","""0.932833388709597""","""-5.3646659309623""","""-22.9291944307147""","""""",,None
4,Africa Western and Central,"""AFW""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""-0.255511351747927""","""1.59294217712238""","""4.97870998351004""","""3.1302314152464""","""1.79876056473303""",...,"""0.0260160622438406""","""-2.51927409834653""","""-0.38269079571522""","""0.140162280475892""","""0.563580469542387""","""-3.45312417907287""","""1.37216006946974""","""1.19266768111382""",,None

In [51]:
# Assign row 0 as column names
cleaned_gdp_df.columns = cleaned_gdp_df.iloc[0]
cleaned_gdp_df.columns = cleaned_gdp_df.columns.str.replace('"', '')  # Remove any quotation marks from column names

# Drop row 0 from the DataFrame
cleaned_gdp_df = cleaned_gdp_df.drop(index=0).reset_index(drop=True)

# Display the cleaned DataFrame
cleaned_gdp_df.sample(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
196,West Bank and Gaza,"""PSE""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""""","""""","""""","""""","""""",...,"""1.37258508832343""","""6.44666146094556""","""-0.577622802403482""","""-1.30481419195327""","""-1.15161366535136""","""-13.4963869730477""","""4.41469534491321""","""1.44237074478619""",,None
34,Central African Republic,"""CAF""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""3.0736281949108""","""-5.4896637926801""","""-2.5915614052098""","""0.0811956533575113""","""-1.09831775021159""",...,"""3.89115882835796""","""2.93809923935532""","""2.59092350135077""","""1.79222030531334""","""0.833009810869896""","""-1.62477557942373""","""-1.21027956389845""","""-2.186536142462""",,None
195,Paraguay,"""PRY""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""4.34624270075223""","""0.799088876797541""","""2.14237617351604""","""1.64808603341366""","""3.57648209891161""",...,"""1.50345764723987""","""2.79275975879854""","""3.34581598704227""","""1.79595163131663""","""-1.72420205098025""","""-2.14847789745059""","""2.69625613798159""","""-1.06017407344768""",,None
141,Lesotho,"""LSO""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""-1.22196001364621""","""11.8357662063166""","""7.27161959846644""","""4.99702500710697""","""-0.93407828607458""",...,"""1.99435847007987""","""2.38028003303062""","""-4.33164641637042""","""-2.70875452075484""","""-1.99859716118449""","""-6.80844470922412""","""0.340031450230541""","""-0.471270300233286""",,None
220,Suriname,"""SUR""","""GDP per capita growth (annual %)""","""NY.GDP.PCAP.KD.ZG""","""""","""1.19078314340462""","""0.179953936137679""","""1.70489489970744""","""2.7395774241356""","""8.23921337727667""",...,"""-4.38340501137017""","""-5.89336062948988""","""0.511689798708389""","""3.86010294966586""","""0.05885853008634""","""-16.911412073134""","""-3.66902298305844""","""1.05437068754199""",,None

In [52]:
# Define a function to remove double quotes from each cell
def remove_quotes(cell_value):
    if cell_value is not None:
        return cell_value.replace('"', '')
    else:
        return cell_value

# Use applymap() to remove double quotes from the entire DataFrame
cleaned_gdp_df_final = cleaned_gdp_df.applymap(remove_quotes)

# Display the first five rows of the cleaned DataFrame
cleaned_gdp_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,2.88516618544072,1.51593791406077,4.91713876742246,4.73833038397655,0.181216309197723,-18.6983243537002,17.2253004018797,,,None
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.34297354000095,5.09399196578835,2.33079606875697,1.72402096043484,2.43621527890161,...,0.166839637757079,-0.490259075567408,-0.10588633336323,-0.169822405441494,-0.587557018399707,-5.42166221698315,1.68355673118708,0.842506639677993,,None
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-1.66641641520391,-0.345802496981889,-0.253593781811986,-1.68857659267114,0.932833388709597,-5.3646659309623,-22.9291944307147,,,None
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511351747927,1.59294217712238,4.97870998351004,3.1302314152464,1.79876056473303,...,0.0260160622438406,-2.51927409834653,-0.38269079571522,0.140162280475892,0.563580469542387,-3.45312417907287,1.37216006946974,1.19266768111382,,None
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-2.64297533030704,-6.01189077751143,-3.63069503801748,-4.67666958432599,-4.01711416103254,-8.67243212911843,-1.95459800636894,-0.096754729759283,,None

In [53]:
# Convert columns to float data type
for column in cleaned_gdp_df_final.columns[55:66]:
    cleaned_gdp_df_final[column] = pd.to_numeric(cleaned_gdp_df_final[column], errors='coerce')

# Display the DataFrame with the specified columns converted to float
cleaned_gdp_df_final.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,2.885166,1.515938,4.917139,4.738330,0.181216,-18.698324,17.225300,,,None
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.34297354000095,5.09399196578835,2.33079606875697,1.72402096043484,2.43621527890161,...,0.166840,-0.490259,-0.105886,-0.169822,-0.587557,-5.421662,1.683557,0.842506639677993,,None
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-1.666416,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.929194,,,None
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511351747927,1.59294217712238,4.97870998351004,3.1302314152464,1.79876056473303,...,0.026016,-2.519274,-0.382691,0.140162,0.563580,-3.453124,1.372160,1.19266768111382,,None
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-2.642975,-6.011891,-3.630695,-4.676670,-4.017114,-8.672432,-1.954598,-0.096754729759283,,None

In [54]:
cleaned_gdp_df_final.dtypes

0
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960               object
                   ...
2020              float64
2021              float64
2022               object
                   object
None               object
Length: 69, dtype: object

In [55]:
# Slice the DataFrame from column index 55 to 65 (inclusive)
selected_columns = cleaned_gdp_df_final.iloc[:, 55:66]
# Get the column names of the selected columns
column_names = selected_columns.columns.tolist()
# Print the column names
print(column_names)

['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']

In [56]:
# Calculate the average for each row in 2015-2022
average = cleaned_gdp_df_final.iloc[:, 55:66].mean(axis=1)
# Add the average values as a new column named "Average" to the DataFrame
cleaned_gdp_df_final['Average_gdp_growth%'] = average

In [42]:
cleaned_gdp_df_final

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,,None,Average_gdp_growth%
0,Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,1.515938,4.917139,4.738330,0.181216,-18.698324,17.225300,,,None,1.646600
1,Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-2.34297354000095,5.09399196578835,2.33079606875697,1.72402096043484,2.43621527890161,...,-0.490259,-0.105886,-0.169822,-0.587557,-5.421662,1.683557,0.842506639677993,,None,-0.848605
2,Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-0.345802,-0.253594,-1.688577,0.932833,-5.364666,-22.929194,,,None,-4.941500
3,Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-0.255511351747927,1.59294217712238,4.97870998351004,3.1302314152464,1.79876056473303,...,-2.519274,-0.382691,0.140162,0.563580,-3.453124,1.372160,1.19266768111382,,None,-0.713198
4,Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,-6.011891,-3.630695,-4.676670,-4.017114,-8.672432,-1.954598,-0.096754729759283,,None,-4.827233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,,...,6.203623,4.038709,3.056665,5.237433,-5.406638,10.999527,4.9247533867139,,None,4.021553
262,Yemen,Rep.,YEM,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,,,,,...,-29.921761,-11.720018,-7.475113,-1.721735,NaN,NaN,,,,-12.709657
263,South Africa,ZAF,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,0.977923938584297,3.06189947695803,4.16549817661469,4.685237419633,2.8922054413778,...,-0.309171,0.766942,0.285736,-0.987175,-7.481093,3.870315,1.18766321355079,,None,-0.642408
264,Zambia,ZMB,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,-1.78768497310053,-5.54148944363011,0.0233605345168826,8.68608586454545,12.9720329002912,...,0.561271,0.331284,0.897347,-1.564237,-5.595733,1.669097,1.89551775169321,,None,-0.616829
265,Zimbabwe,ZWE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,,3.07620994094849,-1.66698919029021,2.98542723959167,-4.14390578333571,1.68298600753299,...,-1.177893,1.974846,2.909395,-8.177320,-9.670405,6.271613,1.32818433636854,,None,-1.311627

In [57]:
gdpgrowth_machine_df=cleaned_gdp_df_final[['Country Name','Average_gdp_growth%']]
gdpgrowth_machine_df.sample(50)

0                                         Country Name  Average_gdp_growth%
25                                             Belarus             1.301849
244                                            Turkiye             4.358060
31                                   Brunei Darussalam            -0.885897
229                                               Chad            -1.716827
144                                         Luxembourg             0.119556
147                           St. Martin (French part)                  NaN
87                                       Guinea-Bissau             0.742053
50                                                Cuba             0.822334
168                                             Malawi             0.887168
65                               Europe & Central Asia             1.170997
158                                               Mali             0.479945
61         East Asia & Pacific (excluding high income)             5.783522
109                                              India             4.347494
243                                            Tunisia            -0.007553
94                                              Guyana             8.162508
205                                       Saudi Arabia             1.170869
24                              Bosnia and Herzegovina             3.751370
49                              Caribbean small states            -0.195175
117                                            Jamaica            -0.025238
213                                            Somalia             3.185604
66                                             Ecuador             0.351355
179                                              Nauru             5.394447
210                                       Sierra Leone             1.779923
233                                           Thailand             1.762241
169                                           Malaysia             2.497935
23                                             Bahamas            -2.273182
97                                            Honduras             1.492175
35                                              Canada             0.688762
165                                         Mozambique             1.478504
184                                           Pakistan             2.359673
111                                            Ireland             6.283110
176                                        Netherlands             0.793770
182                                               Oman            -1.534259
77                                              France             0.649757
128  Latin America & Caribbean (excluding high income)             0.385855
143                                          Lithuania             4.628257
38                                     Channel Islands            -0.064412
166                                         Mauritania             0.986399
175                                          Nicaragua             2.063246
194                                           Portugal             0.595251
42                                            Cameroon             1.058919
186                                               Peru             2.232965
227                               Syrian Arab Republic            -6.726636
142                          Late-demographic dividend             4.505982
246                                           Tanzania             2.485056
262                                              Yemen            -7.008981
110                                     Not classified                  NaN
76                                                Fiji             0.523298
207                                            Senegal             2.001628
203                                             Rwanda             3.970361

In [58]:
# Create the "Output_Jibek" directory if it doesn't exist
output_directory = "../Output_Jibek"
if not os.path.exists(output_directory):
    os.makedirs(output_directory)
# Save the cleaned DataFrame to a CSV file in the specified directory
gdpgrowth_machine_df.to_csv(os.path.join(output_directory, 'gdpgrowth_machine_df'), index=False)