In [39]:
#Import Dependancies
import pandas as pd
import os

In [40]:
#Import File
ip_income = 'Recipient_of IP_Income.csv'
ip_income_df = pd.read_csv(ip_income,  sep="\t")
ip_income_df.head(10)

         Data Source,"World Development Indicators",
0                    Last Updated Date,"2023-06-29",
1  Country Name,"Country Code","Indicator Name","...
2  Aruba,"ABW","Charges for the use of intellectu...
3  Africa Eastern and Southern,"AFE","Charges for...
4  Afghanistan,"AFG","Charges for the use of inte...
5  Africa Western and Central,"AFW","Charges for ...
6  Angola,"AGO","Charges for the use of intellect...
7  Albania,"ALB","Charges for the use of intellec...
8  Andorra,"AND","Charges for the use of intellec...
9  Arab World,"ARB","Charges for the use of intel...

In [41]:
list(ip_income_df)

['Data Source,"World Development Indicators",']

In [42]:
# Get the contents of row 2
row_2_data = ip_income_df.iloc[1]
# Convert row 2 data to a list
columns = row_2_data.tolist()
columns

['Country Name,"Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022",']

In [43]:
# Split columns
split_data = ip_income_df['Data Source,"World Development Indicators",'].str.split(',', n=68, expand=True)

# Create a new DataFrame to store the cleaned data with appropriate column names
split_ip_income_df = pd.DataFrame(
    {
        'Country Name': split_data[0],
        'Country Code': split_data[1],
        'Indicator Name': split_data[2],
        'Indicator Code': split_data[3],
    }
)


# Concatenate the remaining columns from original data
split_ip_income_df = pd.concat([split_ip_income_df, split_data.iloc[:, 4:]], axis=1)
split_ip_income_df = split_ip_income_df.drop(index=0).reset_index(drop=True)

# Display the cleaned DataFrame
split_ip_income_df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,Country Name,"""Country Code""","""Indicator Name""","""Indicator Code""","""1960""","""1961""","""1962""","""1963""","""1964""","""1965""",...,"""2015""","""2016""","""2017""","""2018""","""2019""","""2020""","""2021""","""2022""",,None
1,Aruba,"""ABW""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""8645172.62569832""","""10903194.972067""","""13810224.5810056""","""""","""""","""16533453.287263""","""16848539.3339724""","""10210598.3145219""","""12319999.116496""","""14197498.4744828"","
2,Africa Eastern and Southern,"""AFE""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""5599997.76224089""","""5599997.76224089""","""8399996.64336134""","""15399993.8461625""",...,"""2379213510.25123""","""2368730261.33278""","""2256460184.69738""","""2394607870.65437""","""2552763140.71723""","""2161661760.55854""","""1787646004.50884""","""1671894738.807""","""1895894901.42144""","""1720255710.72539"","
3,Afghanistan,"""AFG""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""10944020.3116408""","""107890.10906887""","""242475.541833949""","""36802.95""","""180660.399927953""","""2402430.87491251""","""4778790.72133592""","""6111813.8157338""","""""",""""","
4,Africa Western and Central,"""AFW""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""278039100.438778""","""289056236.188106""","""276882578.310601""","""273617352.791183""","""278307224.628641""","""332642747.646662""","""500983672.425446""","""436502606.056328""","""518136175.423754""","""254051734.022154"","
5,Angola,"""AGO""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""212220137.27""","""252852819.11""","""264702200""","""212229720""","""221726875.72""","""246614994.79""","""127168951.47""","""129608227.29""","""121666360""","""222726990"","
6,Albania,"""ALB""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""22607333.7766244""","""21881927.417607""","""24578013.7488837""","""23163082.2844536""","""13132426.9115916""","""26412466.5010989""","""34784215.26461""","""38609323.641355""","""34763724.472583""","""31727566.8165585"","
7,Andorra,"""AND""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""""","""""","""""","""""","""""","""""","""264666.163607838""","""482661.270612958""","""596311.549435029""",""""","
8,Arab World,"""ARB""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""611288303.496562""","""570922126.010764""","""637828488.803832""","""728556130.762444""","""601386272.489033""","""647807315.750691""","""669028245.492478""","""635735619.464593""","""762787898.109103""","""301703037.644945"","
9,United Arab Emirates,"""ARE""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""""","""""","""""","""""","""""","""""","""""","""""","""""",""""","

In [44]:
# Assign row 0 as column names
split_ip_income_df.columns = split_ip_income_df.iloc[0]

# Remove any quotation marks from column names
split_ip_income_df.columns = split_ip_income_df.columns.str.replace('"', '')

# Drop row 0 from the DataFrame
split_ip_income_df = split_ip_income_df.drop(index=0).reset_index(drop=True)

# Display the cleaned DataFrame
split_ip_income_df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,,None
0,Aruba,"""ABW""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""8645172.62569832""","""10903194.972067""","""13810224.5810056""","""""","""""","""16533453.287263""","""16848539.3339724""","""10210598.3145219""","""12319999.116496""","""14197498.4744828"","
1,Africa Eastern and Southern,"""AFE""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""5599997.76224089""","""5599997.76224089""","""8399996.64336134""","""15399993.8461625""",...,"""2379213510.25123""","""2368730261.33278""","""2256460184.69738""","""2394607870.65437""","""2552763140.71723""","""2161661760.55854""","""1787646004.50884""","""1671894738.807""","""1895894901.42144""","""1720255710.72539"","
2,Afghanistan,"""AFG""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""10944020.3116408""","""107890.10906887""","""242475.541833949""","""36802.95""","""180660.399927953""","""2402430.87491251""","""4778790.72133592""","""6111813.8157338""","""""",""""","
3,Africa Western and Central,"""AFW""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""278039100.438778""","""289056236.188106""","""276882578.310601""","""273617352.791183""","""278307224.628641""","""332642747.646662""","""500983672.425446""","""436502606.056328""","""518136175.423754""","""254051734.022154"","
4,Angola,"""AGO""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""212220137.27""","""252852819.11""","""264702200""","""212229720""","""221726875.72""","""246614994.79""","""127168951.47""","""129608227.29""","""121666360""","""222726990"","
5,Albania,"""ALB""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""22607333.7766244""","""21881927.417607""","""24578013.7488837""","""23163082.2844536""","""13132426.9115916""","""26412466.5010989""","""34784215.26461""","""38609323.641355""","""34763724.472583""","""31727566.8165585"","
6,Andorra,"""AND""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""""","""""","""""","""""","""""","""""","""264666.163607838""","""482661.270612958""","""596311.549435029""",""""","
7,Arab World,"""ARB""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""611288303.496562""","""570922126.010764""","""637828488.803832""","""728556130.762444""","""601386272.489033""","""647807315.750691""","""669028245.492478""","""635735619.464593""","""762787898.109103""","""301703037.644945"","
8,United Arab Emirates,"""ARE""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""""","""""","""""","""""","""""","""""","""""","""""","""""",""""","
9,Argentina,"""ARG""","""Charges for the use of intellectual property",payments (BoP,"current US$)""","""BM.GSR.ROYL.CD""","""""","""""","""""","""""",...,"""2329270062.45138""","""2098996165.63338""","""2178066123.6149""","""2108388364.21439""","""2350351644.7677""","""2054243292.96211""","""1688980858.85513""","""1149104742.16619""","""1397946195.96373""","""1706885414.8243"","

In [45]:
#Filtered columns for desired years
years_columns = [str(year) for year in range(2010, 2021)]

# Select the desired columns
selected_columns = ['Country Name', 'Country Code'] + years_columns

# Create the new DataFrame
selected_columns = split_ip_income_df[selected_columns]

cleaned_ip_income_df = selected_columns

cleaned_ip_income_df.head(10)

,Country Name,Country Code,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,"""ABW""","""11955307.2625698""","""13184357.5418994""","""14748603.3519553""","""10558659.2178771""","""9720670.39106145""","""8645172.62569832""","""10903194.972067""","""13810224.5810056""","""""","""""","""16533453.287263"""
1,Africa Eastern and Southern,"""AFE""","""1913592059.92824""","""1912270943.60864""","""2068158357.13598""","""2218812932.79466""","""2366000693.41856""","""2379213510.25123""","""2368730261.33278""","""2256460184.69738""","""2394607870.65437""","""2552763140.71723""","""2161661760.55854"""
2,Afghanistan,"""AFG""","""308406.5""","""94761.12""","""27577849.86""","""47084262.04""","""10738034.5335198""","""10944020.3116408""","""107890.10906887""","""242475.541833949""","""36802.95""","""180660.399927953""","""2402430.87491251"""
3,Africa Western and Central,"""AFW""","""247502232.858802""","""262738120.496683""","""266899774.002394""","""251239858.934063""","""283984358.688477""","""278039100.438778""","""289056236.188106""","""276882578.310601""","""273617352.791183""","""278307224.628641""","""332642747.646662"""
4,Angola,"""AGO""","""470000""","""20000""","""6378100""","""3185000""","""224315044.600047""","""212220137.27""","""252852819.11""","""264702200""","""212229720""","""221726875.72""","""246614994.79"""
5,Albania,"""ALB""","""12517993.9317725""","""14487498.7588023""","""12138446.109668""","""12703928.1780979""","""23362460.0492865""","""22607333.7766244""","""21881927.417607""","""24578013.7488837""","""23163082.2844536""","""13132426.9115916""","""26412466.5010989"""
6,Andorra,"""AND""","""""","""""","""""","""""","""""","""""","""""","""""","""""","""""",""""""
7,Arab World,"""ARB""","""385879185.751437""","""392258199.623047""","""435296352.405628""","""422359090.712274""","""590060804.170495""","""611288303.496562""","""570922126.010764""","""637828488.803832""","""728556130.762444""","""601386272.489033""","""647807315.750691"""
8,United Arab Emirates,"""ARE""","""""","""""","""""","""""","""""","""""","""""","""""","""""","""""",""""""
9,Argentina,"""ARG""","""1531726727.27288""","""1526895360.76094""","""1712212409.7066""","""2079139111.3222""","""2216992899.83386""","""2329270062.45138""","""2098996165.63338""","""2178066123.6149""","""2108388364.21439""","""2350351644.7677""","""2054243292.96211"""

In [47]:
# Clean DF and Convert Columns

# Remove the quotation marks from all columns
cleaned_ip_income_df = cleaned_ip_income_df.applymap(lambda x: x.replace('"', '') if isinstance(x, str) else x)

# Convert columns the Years to float data type
for column in cleaned_ip_income_df.columns[2:13]:
    cleaned_ip_income_df[column] = pd.to_numeric(cleaned_ip_income_df[column], errors='coerce')
    
# List of columns from "2010" to "2020"
numerical_columns = ["2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020"]    
    
# Divide the columns by 1 billion
cleaned_ip_income_df[numerical_columns] = cleaned_ip_income_df[numerical_columns].div(1000000)    

# Round all numerical values to two decimal places
cleaned_ip_income_df = cleaned_ip_income_df.round(2)

# Display the updated DataFrame
cleaned_ip_income_df.head()

,Country Name,Country Code,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,11.96,13.18,14.75,10.56,9.72,8.65,10.90,13.81,NaN,NaN,16.53
1,Africa Eastern and Southern,AFE,1913.59,1912.27,2068.16,2218.81,2366.00,2379.21,2368.73,2256.46,2394.61,2552.76,2161.66
2,Afghanistan,AFG,0.31,0.09,27.58,47.08,10.74,10.94,0.11,0.24,0.04,0.18,2.40
3,Africa Western and Central,AFW,247.50,262.74,266.90,251.24,283.98,278.04,289.06,276.88,273.62,278.31,332.64
4,Angola,AGO,0.47,0.02,6.38,3.18,224.32,212.22,252.85,264.70,212.23,221.73,246.61

In [48]:
# Step 1: Melt the DataFrame to transform the years into a separate column
melted_df = cleaned_ip_income_df.melt(id_vars=["Country Name", "Country Code"], var_name="Year", value_name="IP Income($M)")

# Step 2: Sort the DataFrame by "Country Name" and "Year" for better organization
melted_df = melted_df.sort_values(by=["Year", "Country Name"])

# Step 3: Reset the index of the DataFrame
melted_df = melted_df.reset_index(drop=True)

# Step 4: Display the modified DataFrame
melted_df.head()

                  Country Name Country Code  Year  IP Income($M)
0                  Afghanistan          AFG  2010           0.31
1  Africa Eastern and Southern          AFE  2010        1913.59
2   Africa Western and Central          AFW  2010         247.50
3                      Albania          ALB  2010          12.52
4                      Algeria          DZA  2010          10.16

In [49]:
# Export the DataFrame to the CSV file
melted_df.to_csv('Cleaned_Data/IP_Income.csv', index=False)